### ISSUE TITLE
Error: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by shaneostonstowe** [joeldenning/vite-single-spa-root-config#1]
I am working on setting up single-spa with a root config that uses the layout engine.  The root-config was created using `create-single-spa`. The only change is the addition of the vue app to `index.ejs` as shown here: 

``` <script type="systemjs-importmap">
    {
      "imports": {
        "@jrni-studio/studio-shell": "//localhost:3000/src/main.js",
        "@jrni-studio/root-config": "//localhost:9000/jrni-studio-root-config.js"
      }
    }
  </script>
``` 

I have cloned the repo at https://github.com/joeldenning/vite-single-spa-example with no changes. 

When I load the app an error from the vue app's `main.js` is thrown: 

```
Uncaught SyntaxError: application '@jrni-studio/studio-shell' died in status LOADING_SOURCE_CODE: import declarations may only appear at top level of a module
``` 

I am running the app locally.  Note that I do not get this when I use the link:

 https://single-spa-playground.org/playground/instant-test?name=vite-test&framework=vue&useNativeModules=true&url=https%3A%2F%2Flocalhost%3A3000%2Fsrc%2Fmain.js

Is the problem here that I am running the app locally without an override of the vue app?  Or does the use of the layout engine require different config? 

Might you be able to provide some assistance with this? 

Thanks a lot.

**Comment by internettrans** [comment]
In local development, vite produces ES modules (not SystemJS modules), so it's incorrect to load ViteJS apps with `System.import()`. Instead, `import()` should be used. See https://single-spa.js.org/docs/ecosystem-vite#native-modules-vs-systemjs for more details.

Single-spa-layout's `loadApp` function is what determines which one is used for each application. The code below shows how can change it to use the browser's native import for loading vite apps:

```diff
const applications = constructApplications({
  routes,
  loadApp({ name }) {
-    return System.import(name);
+    return import(name);
  },
});
```

One thing you'll notice with that example code is that it would require a native import map (not systemjs import map) to be present for your ViteJS applications. Since native import maps don't have full browser support, you could avoid using them by providing a full URL for each application and then calling `import(fullUrl)` rather than `import(name)`.

Closing this as I don't think it's a bug with single-spa's vite support. Feel free to reopen or comment further.
